# project/
#  ┣ client/
#  ┣ server/
#  ┣ docker-compose.yml
#  ┗ ...
# frontend + backend + mongodb setup

 # run == docker-compose up --build

version: "3.8"
services:
  frontend:
    build: ./client
    container_name: mern_frontend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true #helps react auto-refresh in contianer
    depends-on:
      - backend
    stdin_open: true
    volumes:
      - ./client:/app   # auto reload code changes (dev mode)
  
  backend:
    build: ./server
    container_name: mern_backend
    ports:
      -"5000:5000"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/mern_db
    volumes:
      - ./server:/app   
    depends_on:
      - mongo
  
  mongo:
    image: mongo:latest
    container_name: mern_mongo
    ports:
      -"27017:27017"
    volumes:
      -mongo_data:/data/db

volumes:
  mongo_data: