version: "3.8"
services:
  app:
    build: .
    container_name: node_redis_app
    ports:
      -"5000:5000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    restart: always
  
  redis:
    image: redis:latest
    contianer_name: redis_cache
    ports:
      - "6379:6379"


# node+redis app for caching and queues == when backend use caching or queuing system